ALTER TABLE profile_restore
    ADD COLUMN IF NOT EXISTS created timestamptz NOT NULL DEFAULT now();

ALTER TABLE profile_restore
    DROP CONSTRAINT IF EXISTS profile_restore_fk;

ALTER TABLE profile_restore
    ADD COLUMN IF NOT EXISTS profile_id bigint;

ALTER TABLE profile_restore
    ALTER COLUMN profile_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_profile_restore_profile'
          AND conrelid = 'profile_restore'::regclass
    ) THEN
        ALTER TABLE profile_restore
            ADD CONSTRAINT uk_profile_restore_profile UNIQUE (profile_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_profile_restore_profile'
          AND conrelid = 'profile_restore'::regclass
    ) THEN
        ALTER TABLE profile_restore
            ADD CONSTRAINT fk_profile_restore_profile
            FOREIGN KEY (profile_id) REFERENCES profile(id);
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'profile_restore'
          AND column_name = 'id'
          AND is_identity = 'NO'
          AND column_default IS NULL
    ) THEN
        ALTER TABLE profile_restore
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
