-- Auth DB schema (extracted from resume_db_schema_2026-02-03.sql)
-- Cross-DB foreign keys to profile are intentionally omitted.

CREATE TABLE persistent_logins (
    username character varying(64) NOT NULL,
    series character varying(64) NOT NULL,
    token character varying(64) NOT NULL,
    last_used timestamp without time zone NOT NULL
);

ALTER TABLE ONLY persistent_logins
    ADD CONSTRAINT persistent_logins_pkey PRIMARY KEY (username, series);

CREATE TABLE profile_restore (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token character varying(64) NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    profile_id bigint NOT NULL
);

ALTER TABLE ONLY profile_restore
    ADD CONSTRAINT profile_restore_pkey PRIMARY KEY (id);

ALTER TABLE ONLY profile_restore
    ADD CONSTRAINT profile_restore_uid_key UNIQUE (token);

ALTER TABLE ONLY profile_restore
    ADD CONSTRAINT uk_profile_restore_profile UNIQUE (profile_id);

CREATE TABLE remember_me_token (
    series character varying(64) NOT NULL,
    token character varying(64) NOT NULL,
    last_used timestamp with time zone NOT NULL,
    profile_id bigint NOT NULL,
    username character varying(64) NOT NULL
);

ALTER TABLE ONLY remember_me_token
    ADD CONSTRAINT remember_me_token_pkey PRIMARY KEY (series);

CREATE INDEX idx_remember_me_profile ON remember_me_token USING btree (profile_id);
CREATE INDEX idx_remember_me_username ON remember_me_token USING btree (username);
